/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<usart.h>
#include<scc.h>
#include<operations.h>


int main(void) {
    SysClockConfig();
    Usart2_config();

    while (1) {
        print_menu();
        char option = receiverdata();
        UART2_SendChar(option);
        UART2_SendString("\r\n");

        handle_option(option);
    }
}

